[project]
name = "balatro-engine"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "jayceslesar", email = "jaycesles@gmail.com"},
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm.scripts]
lint.shell = "ruff format && ruff check --fix && mypy ."

[project.optional-dependencies]
dev = [
    "ruff>=0.12.2",
    "mypy>=1.16.1",
    "pytest>=8.4.1",
]
[tool.pdm]
distribution = false


[tool.ruff]
line-length = 120


[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
]
ignore = ["E501","E203","B024","B028","UP037", "UP035", "UP006"]
